### ISSUE TITLE
Exceptions thrown on Android

### ISSUE THREAD

**Issue by karl-baker** [markqvist/NomadNet#18]
Have been experiencing these exceptions on Termux under Android:

![image](https://user-images.githubusercontent.com/31621108/209590449-843dace2-7fb0-4b9f-9df0-a94b2257889d.png)

**Comment by markqvist** [comment]
Thanks for reporting this. They seem to be related to the UI code for the internal log viewer. I will look into what is causing it.

They can be safely ignored for users though. My guess is that something is causing the logviewer to not terminate cleanly.

**Comment by markqvist** [comment]
Closing as fixed in subsequent release.
