### ISSUE TITLE
will not install on python 3.10+ due to netifaces being problematic

### ISSUE THREAD

**Issue by 1stmemberoftheDKcrew** [markqvist/NomadNet#26]
Netifaces (which is now depreciated) does not have binaries available for python 3.10 and above and for some reason doesnt want to build on python 3.10 and above either

maybe switching to [netifaces-plus](https://pypi.org/project/netifaces-plus/) might help

**Comment by markqvist** [comment]
That might indeed help, I will look into whether it is possible to use that instead.

On some distros, it might be a temporary workaround to simply install the distro-supplied `python-netifaces` package.
