### ISSUE TITLE
First Time Information and whole screen cannot be read - text is white-gray

### ISSUE THREAD

**Issue by qwertyuiopzxcvbnmlkjhgfdsa1** [markqvist/NomadNet#28]
Ubuntu 32.04, Gnome, run in docker as in instructions

I cannot read what is written there. Is the docker somehow missing capability of displaying color text? 

![image](https://user-images.githubusercontent.com/92012346/233933036-7e70dbc7-5fd6-44b8-888a-ca1bb0e59435.png)

**Comment by qwertyuiopzxcvbnmlkjhgfdsa1** [comment]
The wrong display colors were because of my system's setting. In Terminal's setting there is an option how to set it
![image](https://user-images.githubusercontent.com/92012346/235059285-0c1262dd-0cba-456d-9e42-f153b030ac39.png)

**Comment by markqvist** [comment]
For future reference, there is an option in the nomadnet config file an `~/.nomadnetwork/config` to set the color theme between light and dark. Most terminals use dark themes nowadays, so that is the default, but if you use a light theme, you can change the nomadnet theme to match.
