### ISSUE TITLE
File downloading directory incorrect.

### ISSUE THREAD

**Issue by faragher** [markqvist/NomadNet#40]
When attempting to download a file from NomadNet, I get the following error:

`[2023-11-29 08:29:05] [Error] An error occurred while handling file response. The contained exception was: [Errno 2] No such file or directory: '/home/<user>/Downloads/RNodeFirmware/1.67/release.json'`

This is a download error that attempts to place the file's entire path into the download directory. I see two options:

1. This is intended behavior, but requires os.makedirs(path, exists_ok=True)
2. This is unintended behavior and the intended path is ~/Downloads/release.json

I don't believe the first is intended. so I will look into making the system function as in situation 2.

**Comment by markqvist** [comment]
Fixed by #41
