### ISSUE TITLE
Reticulum config editing

### ISSUE THREAD

**Issue by RageGamerBoi** [markqvist/NomadNet#44]
Because the NomadNet config is the only one editable from inside NomadNet itself, it leads to confusion when interfaces are added to that file instead of Reticulum's config file.

**Comment by markqvist** [comment]
You can also just edit it in `~/.nomadnetwork/config` with whatever editor you'd like. The built-in editing capability is just for convenience, and a bit broken in some ways. I've thought about removing it altogether, but so far that hasn't happened.

**Comment by markqvist** [comment]
Reticulum interfaces must be added directly in the Reticulum configuration file. The nomadnet configuration is only relevant for the nomadnet program itself.
