### ISSUE TITLE
Hosted page and file refresh not working as expected

### ISSUE THREAD

**Issue by r8io** [markqvist/NomadNet#45]
It appears to me that the hosted page and file refresh intervals are not working as expected in the newly released NomadNet version 0.4.3.

Is far as I can tell they are refreshed continuously all the time. If my observation is wrong please ignore my rather spontaneous solution which I have not tested in any way.

In the `Node.py` file, starting at line 230, I would suggest to update `self.last_page_refresh` and `self.last_file_refresh` to the current time.

```Python
if self.page_refresh_interval > 0:
    if now > self.last_page_refresh + self.page_refresh_interval*60:
        self.last_page_refresh = time.time()
        self.register_pages()
                    
if self.file_refresh_interval > 0:
    if now > self.last_file_refresh + self.file_refresh_interval*60:
        self.last_file_refresh = time.time()
        self.register_files()

```

Since I could not find the two new options in a newly created NomadNet config file, I would suggest to add the following lines to the `NomadNetworkApp.py` file, after line 1051.
```Python
# Automatic rescan interval of the pages directory in minutes.
# Default: int = 0 (no rescan)
page_refresh_interval = 0

# Automatic rescan interval of the files directory in minutes.
# Default: int = 0 (no rescan)
file_refresh_interval = 0
```

**Comment by markqvist** [comment]
Thanks a lot for reporting this and suggesting a fix! Implemented in 1f7302903ab2fc1840c13ac360eb71ec9a86cd29 and will be released soon :)
