### ISSUE TITLE
Announce stream UI stops updating if nomadnet ever has to reconnect to rnsd

### ISSUE THREAD

**Issue by neutralinsomniac** [markqvist/NomadNet#52]
If `rnsd` and `nomadnet` are running, and I restart `rnsd`, causing `nomadnet` to perform a reconnect, the announce stream UI stops updating despite announces showing up in the `nomadnet` log viewer.

**Comment by markqvist** [comment]
Thanks for reporting. I've seen this intermittently as well. If you come up with more information, please do share, cause it definitely shouldn't happen ;)

**Comment by markqvist** [comment]
Fixed in latest RNS.
