### ISSUE TITLE
[0.5.2] Setting node_name makes NomadNet crash on startup

### ISSUE THREAD

**Issue by mehow** [markqvist/NomadNet#59]
0.5.2 introduced a bug where setting node_name in the config file makes NomadNet crash on startup with:
`
[Error] The configuration file is invalid. The contained exception was: invalid literal for int() with base 10: 'None'
`

In https://github.com/markqvist/NomadNet/blame/03a02a9ebc4fb1a2cc985bb48a7fb99b6d1bf5f5/nomadnet/NomadNetworkApp.py#L749 `"node_name"` needs to be replaced with`option`.

**Comment by markqvist** [comment]
Thank you very much! Fixed!
